#ifndef DBFDATABASE_GLOBAL_H
#define DBFDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBFDATABASE_LIBRARY)
#  define DBFDATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBFDATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBFDATABASE_GLOBAL_H
